### ISSUE TITLE
Do we know what we mean by 'bias'?

### ISSUE THREAD

**Issue by dwsinger** [w3c/ai-web-impact#17]
I know it seems obvious, but I am not sure it is. I suspect that in this context, it's using training data that does not match the target/user population. So, for example, if I am to use an ML system in a pediatric hospital, training it on the general population (including adults) is probably biased, just as much as the reverse would be (training on only children, and then using it generally).

However, this becomes hard when the relevant characteristics of the target may change after the database was developed.

Exposing this is super-important, I agree, because it's possible to suffer from 'inherited bias' (there was a bias in the data you selected to train your system).

**Comment by dontcallmedom** [comment]
The document links to the ethics in ML document on bias, which itself quotes a definition as "a systematic skew in decision-making that results in unfair outcomes" from  the [CDEI Review into Bias in Algorithmic Decision-Making](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/938857/Summary_Slide_Deck_-_CDEI_review_into_bias_in_algorithmic_decision-making.pdf).

[A Survey on Bias and Fairness in Machine Learning](https://arxiv.org/pdf/1908.09635.pdf) quotes a definition of fairness as "absence of any prejudice or favoritism toward an individual or group based on their inherent or acquired characteristics".

(this suggests that using a model trained on the general population in the context of a pediatric hospital wouldn't be an illustration of bias - merely a case of using the wrong tool for the job)

Should the document directly quote a definition of bias (rather than just link to it)? should that include a definition of fairness as well (such as the one above)?

**Comment by simoneonofri** [comment]
There is a similar case proposed by Dr Kate Vredenburgh of LSE when [Google Mistakenly Tags Black People as ‘Gorillas,’ Showing Limits of Algorithms](https://www.wsj.com/articles/BL-DGB-42522). 

If can be useful to say that a bias can be generated also by the  _accuracy_ of the data set if it were interesting to specify

**Comment by dontcallmedom** [comment]
another reference: ISO 22989 has the following definition for bias "systematic difference in treatment of certain objects, people or groups in comparison to others"

**Comment by dwsinger** [comment]
"unfair outcomes" seems to move the definition problem to asking what's fair. The ISO definition is better, IMHO.

**Comment by TzviyaSiegman** [comment]
Please see https://dl.acm.org/doi/10.1145/230538.230561 Friedman, B., Nissenbaum, H. (1996) Bias in Computing Systems,. ACM Transactions on Information Systems, 14(3), 330 –347, ACM 1046-8188/96/0700 –0330 for a fuller understanding of technical and computational bias.

**Comment by dwsinger** [comment]
That paper uses "Accordingly, we use the term bias to refer to computer systems that systematically and unfairly discriminate against certain individuals or groups of individuals in favor of others."

However, their initial example is of a biased airline reservation system which effectively preferred US domestic carriers, and carriers aren't individuals…

And again we hit the question of what's 'unfair'.

**Comment by dontcallmedom** [comment]
I have prepared a pull request adding the ISO definition of bias to the document https://github.com/w3c/ai-web-impact/pull/21 

@dwsinger would this address partially or completely this issue?
