### ISSUE TITLE
Typo? - hyphen in “Machine Learning based”?

### ISSUE THREAD

**Issue by danyork** [w3c/ai-web-impact#2]
In Section 4.5, the fifth paragraph begins:

> While some of these tensions are not new (as discussed below), Machine Learning based systems..

The editor in me feels like there should be a hyphen in “Machine Learning-based systems”, although I admit I’m not entirely up-to-speed on the current state of various style guides.  I also did not search the document to see if there are more instances of this phrasing if you choose to change it.

**Comment by koalie** [comment]
@dontcallmedom I concur with @danyork but when I reviewed the document I chose to ignore it for the sake of readability because "Machine Learning-based systems" looks odd, and "Machine-Learning-based systems" is complex. There is just this one occurrence in the document. I suggest to leave as is or flip the words: "systems based on Machine Learning".
